//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ASNA.DataGate.Client;
using ASNA.DataGate.Common;
using ASNA.QSys.Runtime;
using System;
using System.Collections.Generic;


namespace SunFarm.CustomerApp
{
    
    public partial class CUSTINQ
    {
        private FixedString<_10> SETNAME;
        private FixedString<_1> SFCOLOR;
        private FixedDecimal<_2, _0> SFSEL;
        private FixedDecimal<_6, _0> SFCUSTNO;
        private FixedString<_40> SFNAME1;
        private FixedString<_25> SFCSZ;
        private FixedString<_10> CSRREC;
        private FixedString<_10> CSRFLD;
        private FixedString<_10> SCPGM;
        private FixedString<_40> SFOLDNAME;
        private FixedString<_40> SFNAME;
        private FixedString<_35> SFADDR1;
        private FixedString<_35> SFADDR2;
        private FixedString<_30> SFCITY;
        private FixedString<_2> SFSTATE;
        private FixedString<_10> SFPOSTCODE;
        private FixedDecimal<_10, _0> SFFAX;
        private FixedString<_20> SFPHONE;
        private FixedString<_1> SFSTATUS;
        private FixedString<_40> SFCONTACT;
        private FixedString<_40> SFCONEMAL;
        private FixedString<_1> SFYN01;
        private FixedDecimal<_11, _2> CSSALES01;
        private FixedDecimal<_11, _2> CSSALES02;
        private FixedDecimal<_11, _2> CSSALES03;
        private FixedDecimal<_11, _2> CSSALES04;
        private FixedDecimal<_11, _2> CSSALES05;
        private FixedDecimal<_11, _2> CSSALES06;
        private FixedDecimal<_11, _2> CSSALES07;
        private FixedDecimal<_11, _2> CSSALES08;
        private FixedDecimal<_11, _2> CSSALES09;
        private FixedDecimal<_11, _2> CSSALES10;
        private FixedDecimal<_11, _2> CSSALES11;
        private FixedDecimal<_11, _2> CSSALES12;
        private FixedDecimal<_11, _2> CSRETURN01;
        private FixedDecimal<_11, _2> CSRETURN02;
        private FixedDecimal<_11, _2> CSRETURN03;
        private FixedDecimal<_11, _2> CSRETURN04;
        private FixedDecimal<_11, _2> CSRETURN05;
        private FixedDecimal<_11, _2> CSRETURN06;
        private FixedDecimal<_11, _2> CSRETURN07;
        private FixedDecimal<_11, _2> CSRETURN08;
        private FixedDecimal<_11, _2> CSRETURN09;
        private FixedDecimal<_11, _2> CSRETURN10;
        private FixedDecimal<_11, _2> CSRETURN11;
        private FixedDecimal<_11, _2> CSRETURN12;
        private FixedDecimal<_13, _2> SFSALES;
        private FixedDecimal<_13, _2> SFRETURNS;
        private FixedString<_10> aPGMQ;
        private FixedString<_4> aMSGKY;
        private FixedString<Len<_1, _2, _8>> MESSAGETEXT;
        static ILayout CUSTDS_000 = Layout.Packed(9, 0);
        static ILayout CUSTDS_001 = Layout.FixedString(40);
        static ILayout CUSTDS_002 = Layout.FixedString(35);
        static ILayout CUSTDS_003 = Layout.FixedString(35);
        static ILayout CUSTDS_004 = Layout.FixedString(30);
        static ILayout CUSTDS_005 = Layout.FixedString(2);
        static ILayout CUSTDS_006 = Layout.FixedString(10);
        static ILayout CUSTDS_007 = Layout.FixedString(1);
        static ILayout CUSTDS_008 = Layout.Packed(10, 0);
        static ILayout CUSTDS_009 = Layout.FixedString(20);
        static ILayout CUSTDS_010 = Layout.FixedString(5);
        static ILayout CUSTDS_011 = Layout.FixedString(40);
        static ILayout CUSTDS_012 = Layout.FixedString(40);
        static ILayout CUSTDS_013 = Layout.FixedString(1);
        static ILayout CUSTDS_014 = Layout.FixedString(1);
        static ILayout CUSTDS_015 = Layout.FixedString(1);
        static ILayout CUSTSL_000 = Layout.Packed(9, 0);
        static ILayout CUSTSL_001 = Layout.Zoned(4, 0);
        static ILayout CUSTSL_002 = Layout.Zoned(1, 0);
        static ILayout CUSTSL_003 = Layout.Packed(11, 2);
        static ILayout CUSTSL_004 = Layout.Packed(11, 2);
        static ILayout CUSTSL_005 = Layout.Packed(11, 2);
        static ILayout CUSTSL_006 = Layout.Packed(11, 2);
        static ILayout CUSTSL_007 = Layout.Packed(11, 2);
        static ILayout CUSTSL_008 = Layout.Packed(11, 2);
        static ILayout CUSTSL_009 = Layout.Packed(11, 2);
        static ILayout CUSTSL_010 = Layout.Packed(11, 2);
        static ILayout CUSTSL_011 = Layout.Packed(11, 2);
        static ILayout CUSTSL_012 = Layout.Packed(11, 2);
        static ILayout CUSTSL_013 = Layout.Packed(11, 2);
        static ILayout CUSTSL_014 = Layout.Packed(11, 2);
        private static Dictionary<string, string> CUSTOMERL2FormatIDs = new Dictionary<string, string>()
        {
            { "RCUSTOMER", "6su4S42+ard0ZHitdjHOFT1WPw0=" }
        };
        private static Dictionary<string, string> CUSTOMERL1FormatIDs = new Dictionary<string, string>()
        {
            { "RCUSTOMER", "6su4S42+ard0ZHitdjHOFT1WPw0=" }
        };
        private static Dictionary<string, string> CSMASTERL1FormatIDs = new Dictionary<string, string>()
        {
            { "RCSMASTL1", "MNWSCMjX4uCVz4ny/YR2N6c1XTM=" }
        };

        private FixedDecimal<_9, _0> CMCUSTNO
        {
            get
            {
                return this.CUSTDS.GetPacked(0, 9, 0);
            }
            set
            {
                this.CUSTDS.SetPacked(value, 0, 9, 0);
            }
        }
        private FixedString<_40> CMNAME
        {
            get
            {
                return this.CUSTDS.GetString(5, 40);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 5, 40);
            }
        }
        private FixedString<_35> CMADDR1
        {
            get
            {
                return this.CUSTDS.GetString(45, 35);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 45, 35);
            }
        }
        private FixedString<_35> CMADDR2
        {
            get
            {
                return this.CUSTDS.GetString(80, 35);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 80, 35);
            }
        }
        private FixedString<_30> CMCITY
        {
            get
            {
                return this.CUSTDS.GetString(115, 30);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 115, 30);
            }
        }
        private FixedString<_2> CMSTATE
        {
            get
            {
                return this.CUSTDS.GetString(145, 2);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 145, 2);
            }
        }
        private FixedString<_10> CMPOSTCODE
        {
            get
            {
                return this.CUSTDS.GetString(147, 10);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 147, 10);
            }
        }
        private FixedString<_1> CMACTIVE
        {
            get
            {
                return this.CUSTDS.GetString(157, 1);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 157, 1);
            }
        }
        private FixedDecimal<_10, _0> CMFAX
        {
            get
            {
                return this.CUSTDS.GetPacked(158, 10, 0);
            }
            set
            {
                this.CUSTDS.SetPacked(value, 158, 10, 0);
            }
        }
        private FixedString<_20> CMPHONE
        {
            get
            {
                return this.CUSTDS.GetString(164, 20);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 164, 20);
            }
        }
        private FixedString<_5> CMUSRFLGS
        {
            get
            {
                return this.CUSTDS.GetString(184, 5);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 184, 5);
            }
        }
        private FixedString<_40> CMCONTACT
        {
            get
            {
                return this.CUSTDS.GetString(189, 40);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 189, 40);
            }
        }
        private FixedString<_40> CMCONEMAL
        {
            get
            {
                return this.CUSTDS.GetString(229, 40);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 229, 40);
            }
        }
        private FixedString<_1> CMYN01
        {
            get
            {
                return this.CUSTDS.GetString(269, 1);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 269, 1);
            }
        }
        private FixedString<_1> CMYN02
        {
            get
            {
                return this.CUSTDS.GetString(270, 1);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 270, 1);
            }
        }
        private FixedString<_1> CMYN03
        {
            get
            {
                return this.CUSTDS.GetString(271, 1);
            }
            set
            {
                this.CUSTDS.SetString(((string)(value)).AsSpan(), 271, 1);
            }
        }
        private FixedDecimal<_9, _0> CSCUSTNO
        {
            get
            {
                return this.CUSTSL.GetPacked(0, 9, 0);
            }
            set
            {
                this.CUSTSL.SetPacked(value, 0, 9, 0);
            }
        }
        private FixedDecimal<_4, _0> CSYEAR
        {
            get
            {
                return this.CUSTSL.GetZoned(5, 4, 0);
            }
            set
            {
                this.CUSTSL.SetZoned(value, 5, 4, 0);
            }
        }
        private FixedDecimal<_1, _0> CSTYPE
        {
            get
            {
                return this.CUSTSL.GetZoned(9, 1, 0);
            }
            set
            {
                this.CUSTSL.SetZoned(value, 9, 1, 0);
            }
        }
        private void PopulateBufferCUSTDSPFSFLC(AdgDataSet _dataSet)
        {
        }
        private void PopulateFieldsCUSTDSPFSFLC(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("SFLC");
            System.Data.DataRow _row = _table.Row;
            SETNAME = ((string)(_row["SETNAME"]));
        }
        private void PopulateBufferCUSTDSPFSFL1(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("SFL1");
            System.Data.DataRow _row = _table.Row;
            _row["SFCOLOR"] = ((string)(SFCOLOR));
            _row["SFSEL"] = ((decimal)(SFSEL));
            _row["SFCUSTNO"] = ((decimal)(SFCUSTNO));
            _row["SFNAME1"] = ((string)(SFNAME1));
            _row["SFCSZ"] = ((string)(SFCSZ));
        }
        private void PopulateFieldsCUSTDSPFSFL1(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("SFL1");
            System.Data.DataRow _row = _table.Row;
            SFCOLOR = ((string)(_row["SFCOLOR"]));
            SFSEL = ((decimal)(_row["SFSEL"]));
            SFCUSTNO = ((decimal)(_row["SFCUSTNO"]));
            SFNAME1 = ((string)(_row["SFNAME1"]));
            SFCSZ = ((string)(_row["SFCSZ"]));
        }
        private void PopulateBufferCUSTDSPFCUSTREC(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("CUSTREC");
            System.Data.DataRow _row = _table.Row;
            _row["CSRREC"] = ((string)(CSRREC));
            _row["CSRFLD"] = ((string)(CSRFLD));
            _row["SCPGM"] = ((string)(SCPGM));
            _row["SFCUSTNO"] = ((decimal)(SFCUSTNO));
            _row["SFOLDNAME"] = ((string)(SFOLDNAME));
            _row["SFNAME"] = ((string)(SFNAME));
            _row["SFADDR1"] = ((string)(SFADDR1));
            _row["SFADDR2"] = ((string)(SFADDR2));
            _row["SFCITY"] = ((string)(SFCITY));
            _row["SFSTATE"] = ((string)(SFSTATE));
            _row["SFPOSTCODE"] = ((string)(SFPOSTCODE));
            _row["SFFAX"] = ((decimal)(SFFAX));
            _row["SFPHONE"] = ((string)(SFPHONE));
            _row["SFSTATUS"] = ((string)(SFSTATUS));
            _row["SFCONTACT"] = ((string)(SFCONTACT));
            _row["SFCONEMAL"] = ((string)(SFCONEMAL));
            _row["SFYN01"] = ((string)(SFYN01));
            _row["CSSALES01"] = ((decimal)(CSSALES01));
            _row["CSSALES02"] = ((decimal)(CSSALES02));
            _row["CSSALES03"] = ((decimal)(CSSALES03));
            _row["CSSALES04"] = ((decimal)(CSSALES04));
            _row["CSSALES05"] = ((decimal)(CSSALES05));
            _row["CSSALES06"] = ((decimal)(CSSALES06));
            _row["CSSALES07"] = ((decimal)(CSSALES07));
            _row["CSSALES08"] = ((decimal)(CSSALES08));
            _row["CSSALES09"] = ((decimal)(CSSALES09));
            _row["CSSALES10"] = ((decimal)(CSSALES10));
            _row["CSSALES11"] = ((decimal)(CSSALES11));
            _row["CSSALES12"] = ((decimal)(CSSALES12));
            _row["CSRETURN01"] = ((decimal)(CSRETURN01));
            _row["CSRETURN02"] = ((decimal)(CSRETURN02));
            _row["CSRETURN03"] = ((decimal)(CSRETURN03));
            _row["CSRETURN04"] = ((decimal)(CSRETURN04));
            _row["CSRETURN05"] = ((decimal)(CSRETURN05));
            _row["CSRETURN06"] = ((decimal)(CSRETURN06));
            _row["CSRETURN07"] = ((decimal)(CSRETURN07));
            _row["CSRETURN08"] = ((decimal)(CSRETURN08));
            _row["CSRETURN09"] = ((decimal)(CSRETURN09));
            _row["CSRETURN10"] = ((decimal)(CSRETURN10));
            _row["CSRETURN11"] = ((decimal)(CSRETURN11));
            _row["CSRETURN12"] = ((decimal)(CSRETURN12));
        }
        private void PopulateFieldsCUSTDSPFCUSTREC(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("CUSTREC");
            System.Data.DataRow _row = _table.Row;
            CSRREC = ((string)(_row["CSRREC"]));
            CSRFLD = ((string)(_row["CSRFLD"]));
            SFNAME = ((string)(_row["SFNAME"]));
            SFADDR1 = ((string)(_row["SFADDR1"]));
            SFADDR2 = ((string)(_row["SFADDR2"]));
            SFCITY = ((string)(_row["SFCITY"]));
            SFSTATE = ((string)(_row["SFSTATE"]));
            SFPOSTCODE = ((string)(_row["SFPOSTCODE"]));
            SFFAX = ((decimal)(_row["SFFAX"]));
            SFPHONE = ((string)(_row["SFPHONE"]));
            SFSTATUS = ((string)(_row["SFSTATUS"]));
            SFCONTACT = ((string)(_row["SFCONTACT"]));
            SFCONEMAL = ((string)(_row["SFCONEMAL"]));
            SFYN01 = ((string)(_row["SFYN01"]));
        }
        private void PopulateBufferCUSTDSPFSALESREC(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("SALESREC");
            System.Data.DataRow _row = _table.Row;
            _row["SCPGM"] = ((string)(SCPGM));
            _row["SFCUSTNO"] = ((decimal)(SFCUSTNO));
            _row["SFNAME"] = ((string)(SFNAME));
            _row["SFSALES"] = ((decimal)(SFSALES));
            _row["SFRETURNS"] = ((decimal)(SFRETURNS));
        }
        private void PopulateFieldsCUSTDSPFSALESREC(AdgDataSet _dataSet)
        {
        }
        private void PopulateBufferCUSTDSPFKEYS(AdgDataSet _dataSet)
        {
        }
        private void PopulateFieldsCUSTDSPFKEYS(AdgDataSet _dataSet)
        {
        }
        private void PopulateBufferCUSTDSPFMSGSFC(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("MSGSFC");
            System.Data.DataRow _row = _table.Row;
            _row["@PGMQ"] = ((string)(aPGMQ));
        }
        private void PopulateFieldsCUSTDSPFMSGSFC(AdgDataSet _dataSet)
        {
        }
        private void PopulateBufferCUSTDSPFMSGSF(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("MSGSF");
            System.Data.DataRow _row = _table.Row;
            _row["@MSGKY"] = ((string)(aMSGKY));
            _row["@PGMQ"] = ((string)(aPGMQ));
            _row["MESSAGETEXT"] = ((string)(MESSAGETEXT));
        }
        private void PopulateFieldsCUSTDSPFMSGSF(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("MSGSF");
            System.Data.DataRow _row = _table.Row;
            aMSGKY = ((string)(_row["@MSGKY"]));
            aPGMQ = ((string)(_row["@PGMQ"]));
            MESSAGETEXT = ((string)(_row["MESSAGETEXT"]));
        }
        private void PopulateBufferCUSTDSPF(string _recordFormatName, AdgDataSet _dataSet)
        {
            if (string.Equals(_recordFormatName, "SFLC", System.StringComparison.CurrentCultureIgnoreCase))
            {
                this.PopulateBufferCUSTDSPFSFLC(_dataSet);
            }
            else
            {
                if (string.Equals(_recordFormatName, "SFL1", System.StringComparison.CurrentCultureIgnoreCase))
                {
                    this.PopulateBufferCUSTDSPFSFL1(_dataSet);
                }
                else
                {
                    if (string.Equals(_recordFormatName, "CUSTREC", System.StringComparison.CurrentCultureIgnoreCase))
                    {
                        this.PopulateBufferCUSTDSPFCUSTREC(_dataSet);
                    }
                    else
                    {
                        if (string.Equals(_recordFormatName, "SALESREC", System.StringComparison.CurrentCultureIgnoreCase))
                        {
                            this.PopulateBufferCUSTDSPFSALESREC(_dataSet);
                        }
                        else
                        {
                            if (string.Equals(_recordFormatName, "KEYS", System.StringComparison.CurrentCultureIgnoreCase))
                            {
                                this.PopulateBufferCUSTDSPFKEYS(_dataSet);
                            }
                            else
                            {
                                if (string.Equals(_recordFormatName, "MSGSFC", System.StringComparison.CurrentCultureIgnoreCase))
                                {
                                    this.PopulateBufferCUSTDSPFMSGSFC(_dataSet);
                                }
                                else
                                {
                                    if (string.Equals(_recordFormatName, "MSGSF", System.StringComparison.CurrentCultureIgnoreCase))
                                    {
                                        this.PopulateBufferCUSTDSPFMSGSF(_dataSet);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        private void PopulateFieldsCUSTDSPF(string _recordFormatName, AdgDataSet _dataSet)
        {
            if (string.Equals(_recordFormatName, "SFLC", System.StringComparison.CurrentCultureIgnoreCase))
            {
                this.PopulateFieldsCUSTDSPFSFLC(_dataSet);
            }
            else
            {
                if (string.Equals(_recordFormatName, "SFL1", System.StringComparison.CurrentCultureIgnoreCase))
                {
                    this.PopulateFieldsCUSTDSPFSFL1(_dataSet);
                }
                else
                {
                    if (string.Equals(_recordFormatName, "CUSTREC", System.StringComparison.CurrentCultureIgnoreCase))
                    {
                        this.PopulateFieldsCUSTDSPFCUSTREC(_dataSet);
                    }
                    else
                    {
                        if (string.Equals(_recordFormatName, "SALESREC", System.StringComparison.CurrentCultureIgnoreCase))
                        {
                            this.PopulateFieldsCUSTDSPFSALESREC(_dataSet);
                        }
                        else
                        {
                            if (string.Equals(_recordFormatName, "KEYS", System.StringComparison.CurrentCultureIgnoreCase))
                            {
                                this.PopulateFieldsCUSTDSPFKEYS(_dataSet);
                            }
                            else
                            {
                                if (string.Equals(_recordFormatName, "MSGSFC", System.StringComparison.CurrentCultureIgnoreCase))
                                {
                                    this.PopulateFieldsCUSTDSPFMSGSFC(_dataSet);
                                }
                                else
                                {
                                    if (string.Equals(_recordFormatName, "MSGSF", System.StringComparison.CurrentCultureIgnoreCase))
                                    {
                                        this.PopulateFieldsCUSTDSPFMSGSF(_dataSet);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        private void PopulateBufferCUSTOMERL2(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("*FILE");
            System.Data.DataRow _row = _table.Row;
            _row["CMCUSTNO"] = ((decimal)(CMCUSTNO));
            _row["CMNAME"] = ((string)(CMNAME));
            _row["CMADDR1"] = ((string)(CMADDR1));
            _row["CMADDR2"] = ((string)(CMADDR2));
            _row["CMCITY"] = ((string)(CMCITY));
            _row["CMSTATE"] = ((string)(CMSTATE));
            _row["CMPOSTCODE"] = ((string)(CMPOSTCODE));
            _row["CMACTIVE"] = ((string)(CMACTIVE));
            _row["CMFAX"] = ((decimal)(CMFAX));
            _row["CMPHONE"] = ((string)(CMPHONE));
            _row["CMUSRFLGS"] = ((string)(CMUSRFLGS));
            _row["CMCONTACT"] = ((string)(CMCONTACT));
            _row["CMCONEMAL"] = ((string)(CMCONEMAL));
            _row["CMYN01"] = ((string)(CMYN01));
            _row["CMYN02"] = ((string)(CMYN02));
            _row["CMYN03"] = ((string)(CMYN03));
        }
        private void PopulateFieldsCUSTOMERL2(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.SetActive("*FILE");
            System.Data.DataRow _row = _table.Row;
            CMCUSTNO = ((decimal)(_row["CMCUSTNO"]));
            CMNAME = ((string)(_row["CMNAME"]));
            CMADDR1 = ((string)(_row["CMADDR1"]));
            CMADDR2 = ((string)(_row["CMADDR2"]));
            CMCITY = ((string)(_row["CMCITY"]));
            CMSTATE = ((string)(_row["CMSTATE"]));
            CMPOSTCODE = ((string)(_row["CMPOSTCODE"]));
            CMACTIVE = ((string)(_row["CMACTIVE"]));
            CMFAX = ((decimal)(_row["CMFAX"]));
            CMPHONE = ((string)(_row["CMPHONE"]));
            CMUSRFLGS = ((string)(_row["CMUSRFLGS"]));
            CMCONTACT = ((string)(_row["CMCONTACT"]));
            CMCONEMAL = ((string)(_row["CMCONEMAL"]));
            CMYN01 = ((string)(_row["CMYN01"]));
            CMYN02 = ((string)(_row["CMYN02"]));
            CMYN03 = ((string)(_row["CMYN03"]));
        }
        private void PopulateBufferCUSTOMERL1(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("*FILE");
            System.Data.DataRow _row = _table.Row;
            _row["CMCUSTNO"] = ((decimal)(CMCUSTNO));
            _row["CMNAME"] = ((string)(CMNAME));
            _row["CMADDR1"] = ((string)(CMADDR1));
            _row["CMADDR2"] = ((string)(CMADDR2));
            _row["CMCITY"] = ((string)(CMCITY));
            _row["CMSTATE"] = ((string)(CMSTATE));
            _row["CMPOSTCODE"] = ((string)(CMPOSTCODE));
            _row["CMACTIVE"] = ((string)(CMACTIVE));
            _row["CMFAX"] = ((decimal)(CMFAX));
            _row["CMPHONE"] = ((string)(CMPHONE));
            _row["CMUSRFLGS"] = ((string)(CMUSRFLGS));
            _row["CMCONTACT"] = ((string)(CMCONTACT));
            _row["CMCONEMAL"] = ((string)(CMCONEMAL));
            _row["CMYN01"] = ((string)(CMYN01));
            _row["CMYN02"] = ((string)(CMYN02));
            _row["CMYN03"] = ((string)(CMYN03));
        }
        private void PopulateFieldsCUSTOMERL1(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.SetActive("*FILE");
            System.Data.DataRow _row = _table.Row;
            CMCUSTNO = ((decimal)(_row["CMCUSTNO"]));
            CMNAME = ((string)(_row["CMNAME"]));
            CMADDR1 = ((string)(_row["CMADDR1"]));
            CMADDR2 = ((string)(_row["CMADDR2"]));
            CMCITY = ((string)(_row["CMCITY"]));
            CMSTATE = ((string)(_row["CMSTATE"]));
            CMPOSTCODE = ((string)(_row["CMPOSTCODE"]));
            CMACTIVE = ((string)(_row["CMACTIVE"]));
            CMFAX = ((decimal)(_row["CMFAX"]));
            CMPHONE = ((string)(_row["CMPHONE"]));
            CMUSRFLGS = ((string)(_row["CMUSRFLGS"]));
            CMCONTACT = ((string)(_row["CMCONTACT"]));
            CMCONEMAL = ((string)(_row["CMCONEMAL"]));
            CMYN01 = ((string)(_row["CMYN01"]));
            CMYN02 = ((string)(_row["CMYN02"]));
            CMYN03 = ((string)(_row["CMYN03"]));
        }
        private void PopulateBufferCSMASTERL1(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("*FILE");
            System.Data.DataRow _row = _table.Row;
            _row["CSCUSTNO"] = ((decimal)(CSCUSTNO));
            _row["CSYEAR"] = ((decimal)(CSYEAR));
            _row["CSTYPE"] = ((decimal)(CSTYPE));
            _row["CSSALES01"] = ((decimal)(CSSALES01));
            _row["CSSALES02"] = ((decimal)(CSSALES02));
            _row["CSSALES03"] = ((decimal)(CSSALES03));
            _row["CSSALES04"] = ((decimal)(CSSALES04));
            _row["CSSALES05"] = ((decimal)(CSSALES05));
            _row["CSSALES06"] = ((decimal)(CSSALES06));
            _row["CSSALES07"] = ((decimal)(CSSALES07));
            _row["CSSALES08"] = ((decimal)(CSSALES08));
            _row["CSSALES09"] = ((decimal)(CSSALES09));
            _row["CSSALES10"] = ((decimal)(CSSALES10));
            _row["CSSALES11"] = ((decimal)(CSSALES11));
            _row["CSSALES12"] = ((decimal)(CSSALES12));
        }
        private void PopulateFieldsCSMASTERL1(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.SetActive("*FILE");
            System.Data.DataRow _row = _table.Row;
            CSCUSTNO = ((decimal)(_row["CSCUSTNO"]));
            CSYEAR = ((decimal)(_row["CSYEAR"]));
            CSTYPE = ((decimal)(_row["CSTYPE"]));
            CSSALES01 = ((decimal)(_row["CSSALES01"]));
            CSSALES02 = ((decimal)(_row["CSSALES02"]));
            CSSALES03 = ((decimal)(_row["CSSALES03"]));
            CSSALES04 = ((decimal)(_row["CSSALES04"]));
            CSSALES05 = ((decimal)(_row["CSSALES05"]));
            CSSALES06 = ((decimal)(_row["CSSALES06"]));
            CSSALES07 = ((decimal)(_row["CSSALES07"]));
            CSSALES08 = ((decimal)(_row["CSSALES08"]));
            CSSALES09 = ((decimal)(_row["CSSALES09"]));
            CSSALES10 = ((decimal)(_row["CSSALES10"]));
            CSSALES11 = ((decimal)(_row["CSSALES11"]));
            CSSALES12 = ((decimal)(_row["CSSALES12"]));
        }
        private DataStructure buildDSCUSTDS()
        {
            return new DataStructure(CUSTDS_000, CUSTDS_001, CUSTDS_002, CUSTDS_003, CUSTDS_004, CUSTDS_005, CUSTDS_006, CUSTDS_007, CUSTDS_008, CUSTDS_009, CUSTDS_010, CUSTDS_011, CUSTDS_012, CUSTDS_013, CUSTDS_014, CUSTDS_015);
        }
        private DataStructure buildDSCUSTSL()
        {
            return new DataStructure(CUSTSL_000, CUSTSL_001, CUSTSL_002, CUSTSL_003, CUSTSL_004, CUSTSL_005, CUSTSL_006, CUSTSL_007, CUSTSL_008, CUSTSL_009, CUSTSL_010, CUSTSL_011, CUSTSL_012, CUSTSL_013, CUSTSL_014);
        }
    }
}
