//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ASNA.DataGate.Client;
using ASNA.DataGate.Common;
using ASNA.QSys.Runtime;
using System;
using System.Collections.Generic;


namespace YourCompany.YourApplication
{
    
    public partial class ORDDTLINQ
    {
        private FixedString<_1> SDUMMY;
        private FixedDecimal<_3, _0> SLINNBR;
        private FixedDecimal<_9, _0> SITMNBR;
        private FixedDecimal<_9, _4> SQTYORD;
        private FixedString<_69> SCRCUST;
        private FixedDecimal<_9, _0> SORDNUM;
        private FixedDate<_USA, _Default> SORDDATE;
        private FixedString<_15> SORDAMOUNT;
        private FixedString<_15> SORDWEIGHT;
        private FixedDecimal<_1, _0> SFSEL;
        private FixedDecimal<_3, _0> SFLINNBR;
        private FixedDecimal<_9, _0> SFITMNBR;
        private FixedString<_20> SFITMDESC;
        private FixedDecimal<_9, _4> SFPRICE;
        private FixedDecimal<_10, _4> SFQTYORD;
        private FixedDecimal<_10, _4> SFEXTAMT;
        private FixedString<_10> aPGMQ;
        private FixedString<_4> aMSGKY;
        private FixedString<Len<_1, _2, _8>> MESSAGETEXT;
        private FixedDecimal<_9, _0> CMCUSTNO;
        private FixedString<_40> CMNAME;
        private FixedString<_35> CMADDR1;
        private FixedString<_35> CMADDR2;
        private FixedString<_30> CMCITY;
        private FixedString<_2> CMSTATE;
        private FixedString<_10> CMPOSTCODE;
        private FixedString<_1> CMACTIVE;
        private FixedDecimal<_10, _0> CMFAX;
        private FixedString<_20> CMPHONE;
        private FixedString<_5> CMUSRFLGS;
        private FixedString<_40> CMCONTACT;
        private FixedString<_40> CMCONEMAL;
        private FixedString<_1> CMYN01;
        private FixedString<_1> CMYN02;
        private FixedString<_1> CMYN03;
        private FixedDecimal<_9, _0> ITEMNUMBER;
        private FixedString<_50> ITEMDESC;
        private FixedString<_20> ITEMSHRTDS;
        private FixedDecimal<_5, _0> ITEMCATGRY;
        private FixedDecimal<_9, _4> ITEMPRICE;
        private FixedDecimal<_7, _4> ITEMWEIGHT;
        private FixedString<_10> ITEMUNIT;
        private FixedDecimal<_12, _4> ITEMQTYAVL;
        private FixedDecimal<_12, _4> ITEMQTYORD;
        private FixedDecimal<_9, _0> ORDNUM;
        private FixedDecimal<_9, _0> ORDCUST;
        private FixedDate<_ISO, _Default> ORDDATE;
        private FixedDate<_ISO, _Default> ORDSHPDATE;
        private FixedDecimal<_8, _0> ORDDELDATE;
        private FixedDecimal<_3, _0> ORDSHPVIA;
        private FixedDecimal<_13, _4> ORDAMOUNT;
        private FixedDecimal<_13, _4> ORDWEIGHT;
        private FixedDecimal<_9, _2> ORDSHPCHG;
        private FixedDecimal<_9, _0> ORDLINNUM;
        private FixedDecimal<_9, _0> ORDNUMBER;
        private FixedDecimal<_9, _0> ORDITEMNUM;
        private FixedDecimal<_9, _3> ORDLQTY;
        private FixedDecimal<_9, _3> ORDLQTYBKO;
        private FixedDecimal<_9, _3> ORDLQTYSHP;
        private FixedDecimal<_9, _3> ORDLQTYDEL;
        private static Dictionary<string, string> CUSTOMERL1FormatIDs = new Dictionary<string, string>()
        {
            { "RCUSTOMER", "6su4S42+ard0ZHitdjHOFT1WPw0=" }
        };
        private static Dictionary<string, string> ITEMMASTL1FormatIDs = new Dictionary<string, string>()
        {
            { "ITEM", "MYptlBMMlFkTrB+iC4clV88B0MA=" }
        };
        private static Dictionary<string, string> ORDERHDRL2FormatIDs = new Dictionary<string, string>()
        {
            { "RORDRHDR", "HGKtY5i8LuqjN1v8eIQidC7WD6Q=" }
        };
        private static Dictionary<string, string> ORDERLINL2FormatIDs = new Dictionary<string, string>()
        {
            { "RORDLINE", "ZgLaFmi11VaM21ivXYmcwM/P/Bo=" }
        };

        private void PopulateBufferORDDTLINQDMYWINDOW(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("MYWINDOW");
            System.Data.DataRow _row = _table.Row;
            _row["WINTITLE"] = ((string)(WINTITLE));
        }
        private void PopulateFieldsORDDTLINQDMYWINDOW(AdgDataSet _dataSet)
        {
        }
        private void PopulateBufferORDDTLINQDORDLINE(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("ORDLINE");
            System.Data.DataRow _row = _table.Row;
            _row["SDUMMY"] = ((string)(SDUMMY));
            _row["SLINNBR"] = ((decimal)(SLINNBR));
            _row["SITMNBR"] = ((decimal)(SITMNBR));
            _row["SQTYORD"] = ((decimal)(SQTYORD));
        }
        private void PopulateFieldsORDDTLINQDORDLINE(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("ORDLINE");
            System.Data.DataRow _row = _table.Row;
            SDUMMY = ((string)(_row["SDUMMY"]));
            SITMNBR = ((decimal)(_row["SITMNBR"]));
            SQTYORD = ((decimal)(_row["SQTYORD"]));
        }
        private void PopulateBufferORDDTLINQDSFLC(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("SFLC");
            System.Data.DataRow _row = _table.Row;
            _row["SCRCUST"] = ((string)(SCRCUST));
            _row["SORDNUM"] = ((decimal)(SORDNUM));
            _row["SORDDATE"] = ((System.DateTime)(SORDDATE));
            _row["SORDAMOUNT"] = ((string)(SORDAMOUNT));
            _row["SORDWEIGHT"] = ((string)(SORDWEIGHT));
        }
        private void PopulateFieldsORDDTLINQDSFLC(AdgDataSet _dataSet)
        {
        }
        private void PopulateBufferORDDTLINQDSFL1(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("SFL1");
            System.Data.DataRow _row = _table.Row;
            _row["SFSEL"] = ((decimal)(SFSEL));
            _row["SFLINNBR"] = ((decimal)(SFLINNBR));
            _row["SFITMNBR"] = ((decimal)(SFITMNBR));
            _row["SFITMDESC"] = ((string)(SFITMDESC));
            _row["SFPRICE"] = ((decimal)(SFPRICE));
            _row["SFQTYORD"] = ((decimal)(SFQTYORD));
            _row["SFEXTAMT"] = ((decimal)(SFEXTAMT));
        }
        private void PopulateFieldsORDDTLINQDSFL1(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("SFL1");
            System.Data.DataRow _row = _table.Row;
            SFSEL = ((decimal)(_row["SFSEL"]));
            SFLINNBR = ((decimal)(_row["SFLINNBR"]));
            SFITMNBR = ((decimal)(_row["SFITMNBR"]));
            SFITMDESC = ((string)(_row["SFITMDESC"]));
            SFPRICE = ((decimal)(_row["SFPRICE"]));
            SFQTYORD = ((decimal)(_row["SFQTYORD"]));
            SFEXTAMT = ((decimal)(_row["SFEXTAMT"]));
        }
        private void PopulateBufferORDDTLINQDKEYS(AdgDataSet _dataSet)
        {
        }
        private void PopulateFieldsORDDTLINQDKEYS(AdgDataSet _dataSet)
        {
        }
        private void PopulateBufferORDDTLINQDMSGSFC(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("MSGSFC");
            System.Data.DataRow _row = _table.Row;
            _row["@PGMQ"] = ((string)(aPGMQ));
        }
        private void PopulateFieldsORDDTLINQDMSGSFC(AdgDataSet _dataSet)
        {
        }
        private void PopulateBufferORDDTLINQDMSGSF(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("MSGSF");
            System.Data.DataRow _row = _table.Row;
            _row["@MSGKY"] = ((string)(aMSGKY));
            _row["@PGMQ"] = ((string)(aPGMQ));
            _row["MESSAGETEXT"] = ((string)(MESSAGETEXT));
        }
        private void PopulateFieldsORDDTLINQDMSGSF(AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("MSGSF");
            System.Data.DataRow _row = _table.Row;
            aMSGKY = ((string)(_row["@MSGKY"]));
            aPGMQ = ((string)(_row["@PGMQ"]));
            MESSAGETEXT = ((string)(_row["MESSAGETEXT"]));
        }
        private void PopulateBufferORDDTLINQD(string _recordFormatName, AdgDataSet _dataSet)
        {
            if (string.Equals(_recordFormatName, "MYWINDOW", System.StringComparison.CurrentCultureIgnoreCase))
            {
                this.PopulateBufferORDDTLINQDMYWINDOW(_dataSet);
            }
            else
            {
                if (string.Equals(_recordFormatName, "ORDLINE", System.StringComparison.CurrentCultureIgnoreCase))
                {
                    this.PopulateBufferORDDTLINQDORDLINE(_dataSet);
                }
                else
                {
                    if (string.Equals(_recordFormatName, "SFLC", System.StringComparison.CurrentCultureIgnoreCase))
                    {
                        this.PopulateBufferORDDTLINQDSFLC(_dataSet);
                    }
                    else
                    {
                        if (string.Equals(_recordFormatName, "SFL1", System.StringComparison.CurrentCultureIgnoreCase))
                        {
                            this.PopulateBufferORDDTLINQDSFL1(_dataSet);
                        }
                        else
                        {
                            if (string.Equals(_recordFormatName, "KEYS", System.StringComparison.CurrentCultureIgnoreCase))
                            {
                                this.PopulateBufferORDDTLINQDKEYS(_dataSet);
                            }
                            else
                            {
                                if (string.Equals(_recordFormatName, "MSGSFC", System.StringComparison.CurrentCultureIgnoreCase))
                                {
                                    this.PopulateBufferORDDTLINQDMSGSFC(_dataSet);
                                }
                                else
                                {
                                    if (string.Equals(_recordFormatName, "MSGSF", System.StringComparison.CurrentCultureIgnoreCase))
                                    {
                                        this.PopulateBufferORDDTLINQDMSGSF(_dataSet);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        private void PopulateFieldsORDDTLINQD(string _recordFormatName, AdgDataSet _dataSet)
        {
            if (string.Equals(_recordFormatName, "MYWINDOW", System.StringComparison.CurrentCultureIgnoreCase))
            {
                this.PopulateFieldsORDDTLINQDMYWINDOW(_dataSet);
            }
            else
            {
                if (string.Equals(_recordFormatName, "ORDLINE", System.StringComparison.CurrentCultureIgnoreCase))
                {
                    this.PopulateFieldsORDDTLINQDORDLINE(_dataSet);
                }
                else
                {
                    if (string.Equals(_recordFormatName, "SFLC", System.StringComparison.CurrentCultureIgnoreCase))
                    {
                        this.PopulateFieldsORDDTLINQDSFLC(_dataSet);
                    }
                    else
                    {
                        if (string.Equals(_recordFormatName, "SFL1", System.StringComparison.CurrentCultureIgnoreCase))
                        {
                            this.PopulateFieldsORDDTLINQDSFL1(_dataSet);
                        }
                        else
                        {
                            if (string.Equals(_recordFormatName, "KEYS", System.StringComparison.CurrentCultureIgnoreCase))
                            {
                                this.PopulateFieldsORDDTLINQDKEYS(_dataSet);
                            }
                            else
                            {
                                if (string.Equals(_recordFormatName, "MSGSFC", System.StringComparison.CurrentCultureIgnoreCase))
                                {
                                    this.PopulateFieldsORDDTLINQDMSGSFC(_dataSet);
                                }
                                else
                                {
                                    if (string.Equals(_recordFormatName, "MSGSF", System.StringComparison.CurrentCultureIgnoreCase))
                                    {
                                        this.PopulateFieldsORDDTLINQDMSGSF(_dataSet);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        private void PopulateBufferCUSTOMERL1(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("*FILE");
            System.Data.DataRow _row = _table.Row;
            _row["CMCUSTNO"] = ((decimal)(CMCUSTNO));
            _row["CMNAME"] = ((string)(CMNAME));
            _row["CMADDR1"] = ((string)(CMADDR1));
            _row["CMADDR2"] = ((string)(CMADDR2));
            _row["CMCITY"] = ((string)(CMCITY));
            _row["CMSTATE"] = ((string)(CMSTATE));
            _row["CMPOSTCODE"] = ((string)(CMPOSTCODE));
            _row["CMACTIVE"] = ((string)(CMACTIVE));
            _row["CMFAX"] = ((decimal)(CMFAX));
            _row["CMPHONE"] = ((string)(CMPHONE));
            _row["CMUSRFLGS"] = ((string)(CMUSRFLGS));
            _row["CMCONTACT"] = ((string)(CMCONTACT));
            _row["CMCONEMAL"] = ((string)(CMCONEMAL));
            _row["CMYN01"] = ((string)(CMYN01));
            _row["CMYN02"] = ((string)(CMYN02));
            _row["CMYN03"] = ((string)(CMYN03));
        }
        private void PopulateFieldsCUSTOMERL1(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.SetActive("*FILE");
            System.Data.DataRow _row = _table.Row;
            CMCUSTNO = ((decimal)(_row["CMCUSTNO"]));
            CMNAME = ((string)(_row["CMNAME"]));
            CMADDR1 = ((string)(_row["CMADDR1"]));
            CMADDR2 = ((string)(_row["CMADDR2"]));
            CMCITY = ((string)(_row["CMCITY"]));
            CMSTATE = ((string)(_row["CMSTATE"]));
            CMPOSTCODE = ((string)(_row["CMPOSTCODE"]));
            CMACTIVE = ((string)(_row["CMACTIVE"]));
            CMFAX = ((decimal)(_row["CMFAX"]));
            CMPHONE = ((string)(_row["CMPHONE"]));
            CMUSRFLGS = ((string)(_row["CMUSRFLGS"]));
            CMCONTACT = ((string)(_row["CMCONTACT"]));
            CMCONEMAL = ((string)(_row["CMCONEMAL"]));
            CMYN01 = ((string)(_row["CMYN01"]));
            CMYN02 = ((string)(_row["CMYN02"]));
            CMYN03 = ((string)(_row["CMYN03"]));
        }
        private void PopulateBufferITEMMASTL1(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("*FILE");
            System.Data.DataRow _row = _table.Row;
            _row["ITEMNUMBER"] = ((decimal)(ITEMNUMBER));
            _row["ITEMDESC"] = ((string)(ITEMDESC));
            _row["ITEMSHRTDS"] = ((string)(ITEMSHRTDS));
            _row["ITEMCATGRY"] = ((decimal)(ITEMCATGRY));
            _row["ITEMPRICE"] = ((decimal)(ITEMPRICE));
            _row["ITEMWEIGHT"] = ((decimal)(ITEMWEIGHT));
            _row["ITEMUNIT"] = ((string)(ITEMUNIT));
            _row["ITEMQTYAVL"] = ((decimal)(ITEMQTYAVL));
            _row["ITEMQTYORD"] = ((decimal)(ITEMQTYORD));
        }
        private void PopulateFieldsITEMMASTL1(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.SetActive("*FILE");
            System.Data.DataRow _row = _table.Row;
            ITEMNUMBER = ((decimal)(_row["ITEMNUMBER"]));
            ITEMDESC = ((string)(_row["ITEMDESC"]));
            ITEMSHRTDS = ((string)(_row["ITEMSHRTDS"]));
            ITEMCATGRY = ((decimal)(_row["ITEMCATGRY"]));
            ITEMPRICE = ((decimal)(_row["ITEMPRICE"]));
            ITEMWEIGHT = ((decimal)(_row["ITEMWEIGHT"]));
            ITEMUNIT = ((string)(_row["ITEMUNIT"]));
            ITEMQTYAVL = ((decimal)(_row["ITEMQTYAVL"]));
            ITEMQTYORD = ((decimal)(_row["ITEMQTYORD"]));
        }
        private void PopulateBufferORDERHDRL2(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("*FILE");
            System.Data.DataRow _row = _table.Row;
            _row["ORDNUM"] = ((decimal)(ORDNUM));
            _row["ORDCUST"] = ((decimal)(ORDCUST));
            _row["ORDDATE"] = ((System.DateTime)(ORDDATE));
            _row["ORDSHPDATE"] = ((System.DateTime)(ORDSHPDATE));
            _row["ORDDELDATE"] = ((decimal)(ORDDELDATE));
            _row["ORDSHPVIA"] = ((decimal)(ORDSHPVIA));
            _row["ORDAMOUNT"] = ((decimal)(ORDAMOUNT));
            _row["ORDWEIGHT"] = ((decimal)(ORDWEIGHT));
            _row["ORDSHPCHG"] = ((decimal)(ORDSHPCHG));
        }
        private void PopulateFieldsORDERHDRL2(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.SetActive("*FILE");
            System.Data.DataRow _row = _table.Row;
            ORDNUM = ((decimal)(_row["ORDNUM"]));
            ORDCUST = ((decimal)(_row["ORDCUST"]));
            ORDDATE = ((System.DateTime)(_row["ORDDATE"]));
            ORDSHPDATE = ((System.DateTime)(_row["ORDSHPDATE"]));
            ORDDELDATE = ((decimal)(_row["ORDDELDATE"]));
            ORDSHPVIA = ((decimal)(_row["ORDSHPVIA"]));
            ORDAMOUNT = ((decimal)(_row["ORDAMOUNT"]));
            ORDWEIGHT = ((decimal)(_row["ORDWEIGHT"]));
            ORDSHPCHG = ((decimal)(_row["ORDSHPCHG"]));
        }
        private void PopulateBufferORDERLINL2(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.GetAdgTable("*FILE");
            System.Data.DataRow _row = _table.Row;
            _row["ORDLINNUM"] = ((decimal)(ORDLINNUM));
            _row["ORDNUMBER"] = ((decimal)(ORDNUMBER));
            _row["ORDITEMNUM"] = ((decimal)(ORDITEMNUM));
            _row["ORDLQTY"] = ((decimal)(ORDLQTY));
            _row["ORDLQTYBKO"] = ((decimal)(ORDLQTYBKO));
            _row["ORDLQTYSHP"] = ((decimal)(ORDLQTYSHP));
            _row["ORDLQTYDEL"] = ((decimal)(ORDLQTYDEL));
        }
        private void PopulateFieldsORDERLINL2(string _, AdgDataSet _dataSet)
        {
            var _table = _dataSet.SetActive("*FILE");
            System.Data.DataRow _row = _table.Row;
            ORDLINNUM = ((decimal)(_row["ORDLINNUM"]));
            ORDNUMBER = ((decimal)(_row["ORDNUMBER"]));
            ORDITEMNUM = ((decimal)(_row["ORDITEMNUM"]));
            ORDLQTY = ((decimal)(_row["ORDLQTY"]));
            ORDLQTYBKO = ((decimal)(_row["ORDLQTYBKO"]));
            ORDLQTYSHP = ((decimal)(_row["ORDLQTYSHP"]));
            ORDLQTYDEL = ((decimal)(_row["ORDLQTYDEL"]));
        }
    }
}
